#
# Module manifest for module 'AutoDocumentsExample'
#
# Generated by: Mark Kraus
#
# Generated on: 3/5/2017
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'AutoDocumentsExample.psm1'

# Version number of this module.
ModuleVersion = '1.0.1.6'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '687964a5-131e-49cc-b109-7a1ba2385a44'

# Author of this module
Author = 'Mark Kraus'

# Company or vendor of this module
CompanyName = 'Adataum'

# Copyright statement for this module
Copyright = '2017 All Rights reserved'

# Description of the functionality provided by this module
Description = 'AutoDocumentsExample Example Module'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('Public\Add-Widget.ps1','Public\Get-Widget.ps1','Public\Remove-Widget.ps1','Public\Set-Widget.ps1')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Add-Widget','Get-Widget','Remove-Widget','Set-Widget')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Example','Blog')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/markekraus/AutoDocumentsExample/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/markekraus/AutoDocumentsExample'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '# Version 1.0.1.6 (2017-03-25)
## Notes

First Release!

## Functions

### Add-Widget

* Added Add-Widget function
* Adds new widgets to the widget store

### Get-Widget

* Added Get-Widget function
* Retrievs widgets from the widget store

### Remove-Widget

* Added Remove-Widget function
* Removes widgets from the widget store

### Set-Widget

* Added Set-Widget function
* Sets properties on existing wdigest in the widget store.

## Documentation
* First release of automated documentation'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}






