site_name: AutoDocumentsPlaster
repo_url: https://github.com/Corey-Keller/AutoDocumentsPlaster
site_author: Corey Keller
edit_uri: edit/master/docs/
theme: readthedocs
copyright: "AutoDocumentsPlaster is licensed under the <a href='https://github.com/Corey-Keller/AutoDocumentsPlaster/raw/master/LICENSE'>AGPL license"
pages:
  - Home: index.md
  - AutoDocumentsPlaster Basics:
    - What is AutoDocumentsPlaster?: about.md
    - Quick Start: Quick-Start-Installation-and-Example.md
  - Acknowledgements: acknowledgements.md
